# Git URL : https://github.com/realm/SwiftLint
# Reference : https://realm.github.io/SwiftLint/index.html

# SwiftLint 검사에서 제외할 파일 경로 - included에 포함한 것보다 우선적으로 처리
excluded:
  - Pods
  - Memorizing/AppDelegate.swift
  - Memorizing/SceneDelegate.swift
  - Memorizing/View/MyPageView/InfoPolicy.swift

# 기본 규칙이 아닌 규칙들을 활성화
opt_in_rules:
 #- empty_count       # .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다.
 - empty_string      # 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다.
 - multiline_arguments

# 디폴트로 활성화되어있는 규칙 중 비활성화할 규칙을 정하는 키워드
disabled_rules:
- leading_whitespace
- trailing_whitespace
- type_body_length
- todo
- function_parameter_count
- line_length
- type_name

identifier_name:
    allowed_symbols: ["_"]
